### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/ccv-website-nuxt#7]
- /events
- maybe consider adding the calendar to the homepage
- calendar components could be simplified/refactored, but works for now. Components are just a copy from https://github.com/brown-ccv/ccv-calendar

**Comment by mirestrepo** [comment]
Linked to ticket [#127633](https://ithelp.cis-qas.brown.edu/agent/#t:127633).

**Comment by mirestrepo** [comment]
Linked to ticket [#127633](https://ithelp.cis-qas.brown.edu/agent/#t:127633).
