### ISSUE TITLE
pull people images from the content repo

### ISSUE THREAD

**Issue by eldu** [brown-ccv/ccv-website-nuxt#78]
Currently the images are pulling from the old website. As per https://github.com/brown-ccv/ccv-website-content/pull/56 images are now located in the `images/people` folder in the content repo.

Use images from the content repo

**Comment by mirestrepo** [comment]
@ashleysyg if you have time to look into this, it would be great, otherwise we could chat more

**Comment by mirestrepo** [comment]
closed  by #84 and #86
