### ISSUE TITLE
@ashleysyg for a follow on PR - these footer links should probably mostly be `nuxt-link`s and not `a`s

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/ccv-website-nuxt#80]
@ashleysyg for a follow on PR - these footer links should probably mostly be `nuxt-link`s and not `a`s

_Originally posted by @mcmcgrath13 in https://github.com/brown-ccv/ccv-website-nuxt/pull/79#discussion_r793933750_

**Comment by mcmcgrath13** [comment]
closed by #92
