### ISSUE TITLE
Storage service names not appearing in table

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-nuxt#9]
I might be crazy, but it seems to me that the `Comparison Table` is missing its heading on the `/storage` route. In particular, if I select a few of the services buttons on the right (e.g., `Google Drive` and `Stronghold`), the comparison table shows up on when I scroll down, but there are no heading (i.e., I can't tell which column is for Drive and which is Stronghold). 

If I remember correctly, Fernando had implemented this heading a "floating" row that scrolled down as the user went down the screen.

**Comment by paulstey** [comment]
Oh, and I should mention, I've tested this on Firefox and Chrome.

It's broken in Safari, too, but comparison table looks weird in Safari for other reasons. I'll make that its own issue... ¯\_(ツ)_/¯

**Comment by mirestrepo** [comment]
Closing this in favor of #27
